services:
  db:
    image: postgres:16
    container_name: mybudget-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mybudget
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user-pwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./BDD:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: ./Backend
    container_name: backend-BudgetPerso
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  pgdata: {}
